services:
  front:
    build:
      context: ./
    container_name: clima-app
    restart: always
    expose:
      - 3000
    ports:
      - 81:5173
#    networks:
#      -proxy
#networks:
#  proxy:
#    external: true